### ISSUE TITLE
Affichage sur une partie de l'écran après bascule de portrait à paysage

### ISSUE THREAD

**Issue by Sky-git** [Ayuget/Redface#10]
Appareil utilisé : Nexus 7 sous Android 4.2.2

Lors de l'affichage des messages d'un topic, en basculant du mode portrait à paysage, les messages s'affichent sur une partie de l'écran (sur le côté gauche).
Voir les images de l'affichage en portrait et en mode paysage.
Je ne sais pas si c'est à rapprocher de l'issue #1 

Affichage en portrait
![2015-04-03 22 57 28](https://cloud.githubusercontent.com/assets/845584/6992343/d4428778-dac8-11e4-8ef6-0a846665f410.png)

Affichage après bascule en paysage
![2015-04-03 22 57 34](https://cloud.githubusercontent.com/assets/845584/6992345/da405df8-dac8-11e4-9665-8526294b25de.png)

**Comment by Ayuget** [comment]
En partie corrigé.

Il reste un soucis pénible qui fait que lorsqu'on est en paysage et qu'on consulte un topic, on s'attends si on passe en portrait à retrouver le topic qu'on était en train de lire, et au bon endroit (ca rejoint effectivement #1 )

Le soucis technique est qu'il semble qu'on ne puisse pas réaffectuer un fragment d'un container à un autre, ce qui empêche de réutiliser la même instance lors du passage paysage -> portrait. Il faut donc recréer le fragment, ce qui implique recharger le topic à la bonne page, et à la bonne position de scroll.

Rien de techniquement affolant, mais cela implique de corriger #1 dans un premier temps
