### ISSUE TITLE
Bug de retour en haut de la liste des sujets

### ISSUE THREAD

**Issue by Ayuget** [Ayuget/Redface#108]
Issu du forum :

Lorsqu'on est sur un sujet, effectuer un retour arrière renvoie bien sur la liste des sujets, mais on est renvoyé en haut de cette liste.

**Comment by Ayuget** [comment]
À noter que je ne reproduis pas de mon côté :/

**Comment by alaingui** [comment]
Ayuget
pour reproduire c'est très simple, sans rie nfiltrer au niveau des drapeaux tu parcours une liste de sujet s et tu en lis un. En ressortant tu va etre replacé en haut de la liste des sujets (juste après le refresh )
