### ISSUE TITLE
Les liens externes ne s'ouvrent pas...

### ISSUE THREAD

**Issue by Zesheriff** [Ayuget/Redface#112]
En faisant une recherche Google, via le widget barre de recherche, les liens vers HFR ouvrent bien l'application, mais... amènent à la page d'accueil (mes sujets en l'occurrence).

**Comment by Ayuget** [comment]
Merci du bug report, ca sera corrigé dans la prochaine version (2.1.1)

En fait, j'avais déjà remarqué ça et crée l'issue #102
