### ISSUE TITLE
Nouvelles pages non détectées lors d'un rafraîchissement

### ISSUE THREAD

**Issue by Ayuget** [Ayuget/Redface#149]
depuis le dernière version, quand on est dans un sujet et qu'on rafraîchit ça ne rafraîchit que la page en cours. 
Si une nouvelle page est apparue on ne le sait pas.

 

Obligé de revenir à la liste des sujets et de la rafraîchir pour que la nouvelle page soit disponible

**Comment by nbonnec** [comment]
Le problème vient de là : https://github.com/Ayuget/Redface/blob/master/app/src/main/java/com/ayuget/redface/ui/fragment/TopicFragment.java#L327-L333

Le soft considère que ce n'est pas le même topic.

**Comment by Ayuget** [comment]
Ouep bien vu !

Bizarre je n'ai plus les notifications lors de tes commentaires sur les issues, désolé du délai de réponse :)

**Comment by nbonnec** [comment]
Oui c'est bien ce que je me disais, pas de problèmes :D
