### ISSUE TITLE
Blacklist / Liste noire

### ISSUE THREAD

**Issue by Korrozyf** [Ayuget/Redface#156]
Ajouter une fonctionnalité pour cacher les messages de certains membres.

Navigation : 
- Lorsqu'on affiche une page d'un topic, tous les messages des membres listés dans la liste noire ne sont pas affichés.
- Option contextuelle en touchant le pseudo d'un membre : "Ajouter à la liste noire".

Options de l'application : 
- Ajouter un menu "Gérer la liste noire".

Menu "Gérer la liste noire" : 
- Lister les pseudo des membres ajoutés en liste noir par l'utilisateur.
- Menu contextuel lorsqu'on touche un pseudo "retirer de la liste noire".

Cas des citations : 
- Cacher dans les messages des membres qui s'affichent, les citations de messages de pseudos dans la liste noire.

Point d'attention : 
- Si le stockage des pseudo ne se fait pas par un ID unique, se méfier de la casse sur les pseudos qui peuvent varier.

J'espère ne rien avoir oublié dans le descriptif. :) Merci d'avance m'sieur ! ;)

**Comment by nbonnec** [comment]
Pour info, j'ai commencé à implémenter la fonction.

**Comment by Ayuget** [comment]
Merci encore pour ce gros boulot !
