### ISSUE TITLE
fitioure : possibilité de refresh la liste des sujets depuis le bas de page 

### ISSUE THREAD

**Issue by jean-clovis** [Ayuget/Redface#157]
possibilité de refresh la liste des sujets depuis le bas de page comme ca se fait en haut de page. 
Tout bête et pratique quand on veut voir les nouveaux posts de la cat. discussion par exemple :)

**Comment by nbonnec** [comment]
Il y a un bouton refresh sur le bandeau non ?

**Comment by jean-clovis** [comment]
je parle de cette feature mais en bas de la liste des sujets, quand le bouton refresh n'est plus visible  ;) 
![capture d ecran_20160914_001](https://cloud.githubusercontent.com/assets/6710472/18529823/f9948a7e-7ace-11e6-9937-7ff795d5d2c6.png)

**Comment by jean-clovis** [comment]
Je crois qu'on parle de "pulley menu" dont nous sommes des habitués sous sailfish OS :p

**Comment by nbonnec** [comment]
C'est pas trop un pattern android normalement.

**Comment by jean-clovis** [comment]
dommage, ca aurait évité de remonter en haut de page :(


________________________________
De : Nicolas Bonnec <notifications@github.com>
Envoyé : vendredi 16 septembre 2016 10:50
À : Ayuget/Redface
Cc : Julien Fossati; Author
Objet : Re: [Ayuget/Redface] fitioure : possibilité de refresh la liste des sujets depuis le bas de page (#157)


C'est pas trop un pattern android normalement.

-

**Comment by nbonnec** [comment]
Mais normalement si tu remontes un peu, la toolbar redescend et tu peux appuyer sur le bouton refresh en haut à droite.

**Comment by jean-clovis** [comment]
Oh god, j'avions point vu ! 
Workaround accepted :D

À dim. sept. 18 15:06:44 2016 GMT+0200, Nicolas Bonnec a écrit :
> Mais normalement si tu remontes un peu, la toolbar redescend et tu peux appuyer sur le bouton refresh en haut à droite.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Ayuget/Redface/issues/157#issuecomment-24784664

-- 
Envoyé depuis mon Jolla
