### ISSUE TITLE
Ajouter un thème noir

### ISSUE THREAD

**Issue by Ayuget** [Ayuget/Redface#18]
Il serait sympa d'avoir un thème avec une dominante complètement noire, notamment pour les possesseurs d'écrans OLED.

Pourquoi pas mettre une barre d'action de couleur sombre au passage, pour contenter ceux qui trouvent le rouge des thèmes principaux trop agressif :)

**Comment by Sky-git** [comment]
A clore avec la dernière version v2.0.1 
![Thème foncé]
(http://reho.st/preview/self/ce645993e2b23864b72df58d4a46e82a6de9e42c.jpg)

**Comment by Ayuget** [comment]
Corrigé en 2.0.1 effectivement ! :)
