### ISSUE TITLE
Ajouter un spinner de chargement lors de la recherche de smileys

### ISSUE THREAD

**Issue by Ayuget** [Ayuget/Redface#26]
Nécessaire pour indiquer à l'utilisateur que la recherche est en cours et ne pas qu'il ai l'impression que rien ne se passe.

De même, si aucun résultat n'est remonté, l'indiquer clairement

**Comment by Korrozyf** [comment]
Je dirai qu'il faut que le spinner apparaisse aussi lorsqu'on valide un message. :) Je crois qu'il y en a un sur un chargement de topic et changement de page. Mais pas pour la validation ni l'édition d'un message.

Il y a peut-être d'autres situations actuelles ou à venir qui en nécessiteront un : suppression d'un message / suppression d'un drapeau, etc.

**Comment by Ayuget** [comment]
Déjà implémenté, je ferme :)
