### ISSUE TITLE
Liste de topics favoris/cyan

### ISSUE THREAD

**Issue by Niks4925** [Ayuget/Redface#3]
Dans la liste de topic par favoris et cyan, il apparaît tous les topics y compris ceux qui n'ont pas de nouveaux messages.
Le forum affiche simplement ceux qui ont de nouveaux messages non lus.
ça serait plus lisible d'avoir le même comportement.

**Comment by Sky-git** [comment]
En fait, l'affichage des favoris et drapeaux cyans dépend depuis quelle "page" l'affichage des topic se fait :
- depuis la page d'accueil, avec toutes les catégories, seuls les topics avec des nouveaux messages non lus sont affichés (le comportement décrit)
- depuis la page d'une catégorie, tout les topics, même ceux sans nouveaux messages à lire, apparissent

**Comment by Ayuget** [comment]
Corrigé de la manière suivante :

* Ajout d'une option (désactivée par défaut) pour ne pas afficher dans la liste des drapeaux les sujets entièrement lus
* Les sujets entièrement lus apparaissent (lorsqu'ils sont affichés bien sûr :) ) en "grisé" afin qu'ils ne soient pas en évidence
