### ISSUE TITLE
Anciens avatars affichés dans certains cas

### ISSUE THREAD

**Issue by Ayuget** [Ayuget/Redface#33]
Certains users semblent touchés par ce bug, a creuser !

**Comment by Sky-git** [comment]
Comme dit sur le forum, c'est bizarre. L'URL d'accès à l'avatar courant semble bien être : "http://forum-images.hardware.fr/images/mesdiscussions-{user_id}.jpg"

Il faut peut-être poser la question aux personnes développant les applications pour les autres plateformes, voir à celles gérant le forum.

**Comment by Ayuget** [comment]
Bon, je viens de me rendre compte que certains users avaient des .gif, ce qui pourrait expliquer le phénomène.

Il faudrait parser le profil pour récupérer l'avatar courant.

**Comment by Sky-git** [comment]
A clore aussi (v2.0.1)
