### ISSUE TITLE
Version 'donate'

### ISSUE THREAD

**Issue by LeRiton** [Ayuget/Redface#43]
:o

**Comment by Sky-git** [comment]
Réponse sur [le forum](http://forum.hardware.fr/forum2.php?config=hfr.inc&cat=23&subcat=550&post=29332&page=18&p=1&sondage=0&owntopic=1&trash=0&trash_post=0&print=0&numreponse=0&quote_only=0&new=0&nojs=0#t1921132) :
> A l'occasion de la sortie de la 1.1.0, je mettrais en place un système de don via Paypal (je ne souhaite pas mettre d'achat intégré pour gérer les dons, car cela oblige normalement à mettre son adresse physique sur le descriptif de l'application :O )

**Comment by Sky-git** [comment]
Je pense que ce ticket peut-être clos en "wontfix" sachant qu'il y a le lien PayPal de disponible sur le site : https://www.paypal.me/ayuget

**Comment by Ayuget** [comment]
Effectivement, je préfère passer par des dons :)

Merci à tous ceux qui ont donné !!!
