### ISSUE TITLE
Texte caché par le bouton de reponse

### ISSUE THREAD

**Issue by Korrozyf** [Ayuget/Redface#54]
Lorsqu'on est sur une page qui ne peut pas scroller vers le bas car pas assez de message et que du texte est présent jusqu'en bas de page alors le bouton de réponse est présent en permanence et empêche la lecture du texte qu'il cache. 
Comme on ne peut pas scroller il disparaît pas et si on tente de tirer la page on voit apparaître le bouton de refresh.

**Comment by Ayuget** [comment]
Espace ajouté en bas de page pour empêcher ça. En attendant mieux.
