### ISSUE TITLE
Scrolling capricieux

### ISSUE THREAD

**Issue by Ayuget** [Ayuget/Redface#77]
Il y a pas mal de soucis de scrolling au sein de l'application, il faudrait les corriger :)

- lorsqu'on revient sur l'application, la page se recharge et on perd sa position sur la page

- après avoir posté un message, on est systématiquement envoyé en bas de page,

- ....

**Comment by davidsan** [comment]
Il y a aussi la position du scroll qui n'est pas restaurée après une rotation.
