### ISSUE TITLE
[Affichage] Temps ecoule depuis le dernier post 

### ISSUE THREAD

**Issue by camcha** [Ayuget/Redface#90]
Dans l'affichage de la liste des topics en mode non compact, le temps ecoule depuis le dernier post est calcule sur l'heure de Paris (GMT +01:00) et non l'heure locale.

Exemple : me situant en zone GMT +11:00, le temps ecoule depuis le dernier post affiche "pseudoXXX-10 hours ago" hors il s'agit d'un post datant de quelques minutes seulement.

**Comment by Ayuget** [comment]
Doublon de #4 :)

Corrigé bientôt, ca commence à m'énerver !
