### ISSUE TITLE
Style incorrect de la status bar après rotation / changement de contexte

### ISSUE THREAD

**Issue by Korrozyf** [Ayuget/Redface#92]
Depuis la maj du 16/03, la barre de notification re-deviens rouge quand on retourne dans l'application quand on est en thème nuit. 

Quand on ferme et relance l'application, elle est bien grise/noire. Mais un coup d'arrière plan, premier plan et elle repasse rouge.

**Comment by Ayuget** [comment]
Effectivement, bien vu !

**Comment by Korrozyf** [comment]
My pleasure. ;)

Encore merci pour tout le taff que tu fais sur cette appli. :)
