### ISSUE TITLE
Notification des MP

### ISSUE THREAD

**Issue by Pressur3** [Ayuget/Redface#94]
Le clic sur une notification de message privé quand on en a plusieurs d'un coup n'amène pas sur le bon message privé.

Exemple j'ai 2 notifications de MP : 1 de Plic et 1 de Ploc. Le clic sur la notification du MP de Plic amène sur celui de Ploc. Pas étudié avec 3+ MP mais j'ai l'impression que toutes les notifs amènent au premier MP en date !

@Galaxy S5

**Comment by Ayuget** [comment]
Oups, me semblait avoir testé à l'époque mais visiblement ça merdouille bien :-)
